### ISSUE TITLE
Exception when running contacts.sql

### ISSUE THREAD

**Issue by kenneth-reitz** [digitalocean/databases#3]
```
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) syntax error at or near "2"
LINE 83: 2 Mrs. Catherine Emard II +1002168309791 74477 Mohamed Divid...
```

**Comment by kamaln7** [comment]
Can you try this export instead? The old one is from `pg_dump` and this one is exported using TablePlus: https://kmln.sr/VNeiq6K

**Comment by kenneth-reitz** [comment]
Ah, I'm using PG 11. I think that's the problem. Can you create a dump for each pg version?

**Comment by kenneth-reitz** [comment]
trying your dump now, it looks like it should be fine
